name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  FLUTTER_VERSION: '3.16.0'

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true
      
      - name: Show Flutter version and directory structure
        run: |
          flutter --version
          pwd
          ls -la
          ls -la assets || true
          ls -la assets/icons || true
      
      - name: Enable web
        run: flutter config --enable-web
      
      - name: Install dependencies
        run: |
          flutter clean
          flutter pub get
          flutter doctor -v
      
      - name: Create required directories and files
        run: |
          mkdir -p assets/icons assets/images
          convert -size 192x192 xc:transparent -fill "#4CAF50" -draw "circle 96,96 96,0" assets/icons/Icon-192.png || true
          convert -size 512x512 xc:transparent -fill "#4CAF50" -draw "circle 256,256 256,0" assets/icons/Icon-512.png || true
          ls -la assets/icons
      
      - name: Build
        run: |
          flutter build web --web-renderer canvaskit --release --base-href /culinar-ai/
          ls -la build/web
          ls -la build/web/assets || true
      
      - name: Setup Pages
        uses: actions/configure-pages@v3
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'build/web'
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
        with:
          token: ${{ github.token }}
